# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**3)** Cree un array tridimensional de flotantes `c` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [2]:
# 2.1)
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#2.2)
b = np.array([[1.5,2,3],[4,5,6]],dtype=np.float32)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [4]:
c = np.array([[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]],dtype=np.float64)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## **Ejercicio 3)** Inicializando arrays

**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**5)** Utilice `np.full` para crear un array bidimensional llamado `e` de entradas iguales a `7`, y de dimesiones `(2,2)`.

**6)** Utilice `np.eye` para crear una matriz identidad llamada `f` de dimensiones 2x2.

**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [5]:
# 3.1) 
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#3.2)
ones_array = np.ones((2,3,4))
ones_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
#3.3)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [8]:
#3.4)
g = np.linspace(0,9,9)
g

array([0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ])

In [9]:
#3.5)
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [10]:
#3.6)
f = np.eye(2,2)
f

array([[1., 0.],
       [0., 1.]])

In [11]:
#3.7)
h = np.random.random((2,2))
h

array([[0.81794528, 0.22670236],
       [0.41811984, 0.71559628]])

In [12]:
#3.8)
i = np.empty((3,2))
i

array([[4.98082036e-310, 0.00000000e+000],
       [4.44659081e-323,             nan],
       [0.00000000e+000, 4.98200747e-310]])

## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**2)** Utilizando la función `len()`, determine el *largo* del array `a`.

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [13]:
# 4.1)
a.shape

(3,)

In [14]:
#4.2)
len(a)

3

In [15]:
#4.3)
b.ndim

2

In [16]:
#4.4)
e.size

4

In [17]:
#4.5)
b.dtype

dtype('float32')

In [18]:
b.dtype.name

'float32'

In [19]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

**2)** Cree un array que contenga elementos de tipo `np.float32`.

**3)** Cree un array que contenga elementos de tipo `np.complex128`.

**4)** Cree un array que contenga elementos de tipo `np.bool`.

**5)** Cree un array que contenga elementos de tipo `np.object`.

**6)** Cree un array que contenga elementos de tipo `np.bytes_`.

**7)** Cree un array que contenga elementos de tipo `np.str_`.

In [20]:
# 5.1)
array_a = np.array([1,2,3,4,5],dtype = np.int64)
array_a 

array([1, 2, 3, 4, 5])

In [21]:
#5.2)
array_b = np.array([1,2,3,4,5],dtype = np.float32)
array_b 

array([1., 2., 3., 4., 5.], dtype=float32)

In [22]:
#5.3)
array_c = np.array([1,2,3,4,5],dtype = np.complex128)
array_c 

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [23]:
#5.4)
array_d = np.array([False,True,True],dtype = np.bool)
array_d 

array([False,  True,  True])

In [24]:
#5.5)
array_e = np.array([np.array([1,2,3]),np.array([1,2])],dtype = object)
array_e 

array([array([1, 2, 3]), array([1, 2])], dtype=object)

In [25]:
#5.6)
array_f = np.array(["bytes","no se"],dtype = np.bytes_)
array_f 

array([b'bytes', b'no se'], dtype='|S5')

In [26]:
#5.7)
array_g = np.array(["string","no entiendo que tipo es bytes"],dtype = np.bytes_)
array_g 

array([b'string', b'no entiendo que tipo es bytes'], dtype='|S29')

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la resta `a-b`. Explique lo que ocurre.

**3)** Compare el anterior resultado con el uso de `np.substract`.

**4)** Calcule la suma `a+b` de los arrays `a` y `b`.

**5)** Compare el anterior resultado con el uso de `np.add`.

**6)** Calcule la división punto a punto  `a/b` de `a` y `b`.

**7)** Compare el anterior resultado con el uso de `np.divide`.

**8)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

**9)** Compare el anterior resultado con el uso de `np.multiply`.

**10)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

**11)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

**12)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

**13)** Calcule el coseno punto a punto  `np.cos(b)` de `b`.

**14)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**16)** Compare el anterior resultado con el uso de `np.dot`.

**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [27]:
#6.1)
g = a-b
g 

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
#6.2)
print(" se suma a en ambas filas de -b ")
print("a.shape : ",a.shape)
print("b.shape:", b.shape)

 se suma a en ambas filas de -b 
a.shape :  (3,)
b.shape: (2, 3)


In [29]:
#6.3)
np.subtract(a,b) # es lo mismo

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [30]:
#6.4)
a+b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [31]:
#6.5)
np.add(a,b) # es lo mismo

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [32]:
#6.6)
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [33]:
#6.7)
np.divide(a,b) # es lo mismo

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [34]:
#6.8)
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [35]:
#6.9)
np.multiply(a,b)# es lo mismo

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [36]:
#6.10)
np.exp(b)

array([[  4.481689 ,   7.3890557,  20.085537 ],
       [ 54.59815  , 148.41316  , 403.42877  ]], dtype=float32)

In [37]:
#6.11)
np.sqrt(b)

array([[1.2247449, 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [38]:
#6.12)
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [39]:
#6.13)
np.cos(b)

array([[ 0.0707372 , -0.4161468 , -0.9899925 ],
       [-0.6536436 ,  0.28366217,  0.96017027]], dtype=float32)

In [40]:
#6.14)
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [41]:
#6.15)
e.dot(f)


array([[7., 7.],
       [7., 7.]])

In [42]:
#6.16)
np.dot(e,f)

array([[7., 7.],
       [7., 7.]])

In [43]:
#6.17)
'''

Si multiplicás vectores 1D, np.dot devuelve un escalar (producto interno).

np.dot([1, 2], [3, 4])  # 1*3 + 2*4 = 11


Si multiplicás matrices 2D, np.dot hace multiplicación matricial y devuelve otra matriz.

np.dot([[a, b], [c, d]], [[e, f], [g, h]])  
# -> matriz 2x2

'''

'\n\nSi multiplicás vectores 1D, np.dot devuelve un escalar (producto interno).\n\nnp.dot([1, 2], [3, 4])  # 1*3 + 2*4 = 11\n\n\nSi multiplicás matrices 2D, np.dot hace multiplicación matricial y devuelve otra matriz.\n\nnp.dot([[a, b], [c, d]], [[e, f], [g, h]])  \n# -> matriz 2x2\n\n'

## **Ejercicio 7)** Comparando arrays

**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [44]:
# 7.1)
a == b

array([[False,  True,  True],
       [False, False, False]])

In [45]:
#7.2)
a<b

array([[ True, False, False],
       [ True,  True,  True]])

In [46]:
#7.3)
np.array_equal(a,b)

False

## **Ejercicio 8)** *Copiando* arrays

**1)** Use `.view()` para crear una vista llamada `h` del array `a`.

**2)** Use `.copy()` para crear una copia del array `a`.

In [47]:
# 8.1)
h = a.view()
h    # la diferencia es que si se modifica una vista , se modifica tambbien el array originakl, es como un puntero nuevo que apnta al mismo dato

array([1, 2, 3])

In [48]:
#8.2)
a_copy = a.copy()
a_copy

array([1, 2, 3])

## **Ejercicio 9)** Ordenado

**1)** Use `.sort()` para ordenar los elementos de `a`.

**2)** Ordene los elementos de `c` a lo largo del eje `0`. Explique.

In [49]:
# 9.1)
a = a[::-1] 
print("a(al reves)=",a)
a.sort()
a

a(al reves)= [3 2 1]


array([1, 2, 3])

In [50]:
#9.2) 
np.sort(c,axis=0)

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [51]:
array_kk =  np.array([[[6. , 5, 4. ],
        [2. , 1.5 , 3. ]],

       [[20. , 2. , 7. ],
        [4. , 5. , 6. ]]])


np.sort(array_kk,axis=1)

array([[[ 2. ,  1.5,  3. ],
        [ 6. ,  5. ,  4. ]],

       [[ 4. ,  2. ,  6. ],
        [20. ,  5. ,  7. ]]])

## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays

**1)** Seleccione el segundo elemento de `a`.

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**3)** Seleccione el rango `[0:2]` de elementos de `a`.

**4)** Seleccione los elementos de `b` en el rango `[0:2]` de filas y la columna `1`.

**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**6)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**8)** Seleccione los elementos de `a` que sean menores que dos.

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [52]:
# 10.1)
a[1]

np.int64(2)

In [53]:
#10.2)
b[0][1]

np.float32(2.0)

In [54]:
#10.3)
a[0:2]

array([1, 2])

In [55]:
#10.4)
b[0][0:2]

array([1.5, 2. ], dtype=float32)

In [56]:
#10.5)
b[0:1]

array([[1.5, 2. , 3. ]], dtype=float32)

In [57]:
#10.6)
print(c[1,...])
print("------------------")
print(c[1,:,:])
#si, son lo mismo

[[3. 2. 1.]
 [4. 5. 6.]]
------------------
[[3. 2. 1.]
 [4. 5. 6.]]


In [58]:
#10.7)
a[::-1]

array([3, 2, 1])

In [59]:
#10.8)
a[a<2]

array([1])

In [60]:
#10.9)
indices_fila = [1,0,1,0]
indices_col = [0,1,2,0]
b[indices_fila,indices_col]

array([4. , 2. , 6. , 1.5], dtype=float32)

In [61]:
b[[1,1,1,1]]

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]], dtype=float32)

In [62]:
#10.10)
# 1. Seleccionamos las filas en el orden deseado
filas_seleccionadas = b [[1 , 0 , 1 , 0]]
# Esto crea una nueva matriz 4x3 con las filas repetidas
# [[4. 5. 6.]
# [1.5 2. 3.]
# [4. 5. 6.]
# [1.5 2. 3.]]
# 2. De este resultado , seleccionamos los elementos usando indices de columna
# La logica es la misma que el punto anterior , combinando los indices
columnas_a_seleccionar = [0 , 1 , 2 , 0]
resultado_final = b [[1 , 0 , 1 , 0] , columnas_a_seleccionar ]
print ( resultado_final )
# Salida : [4. 2. 6. 1.5]

[4.  2.  6.  1.5]


## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [63]:
# 11.1)
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]], dtype=float32)

In [64]:
#11.2)
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para *achatar* el array `b`.

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.

**3)** Que indica aquí el signo negativo del segundo índice?

In [65]:
# 12.1)
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ], dtype=float32)

In [66]:
#12.2)
g.reshape((3,-2))
#12.3) es lo mismo que poner un -1, el signo calcula automaticamente la dimension faltante, hace 6/3

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## **Ejercicio 13)** Agregando y quitando elementos

**1)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [67]:
# 13.1)
np.resize(h,(2,6))

array([[3, 2, 1, 3, 2, 1],
       [3, 2, 1, 3, 2, 1]])

In [68]:
# 13.2)
np.append(h,g)
#aplana todo y despues los concatena en el orden de los parametros

array([ 3. ,  2. ,  1. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [75]:
# 13.3)
np.insert(a,1,5)

array([1, 5, 2, 3])

In [76]:
# 13.4)
np.delete(a,1)

array([1, 3])

## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.

In [79]:
# 14.1)
np.concatenate((a,d))

array([ 1,  2,  3, 10, 15, 20])

In [81]:
# 14.2)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [82]:
#14.3)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

## **Ejercicio 15)** *Separando* arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por

    [[1, 2, 3, 4],
    [2, 0, 0, 2],
    [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

In [84]:
# 15.a)
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [85]:
#15.b)
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]

In [86]:
#15.c)
z = np.array([[1, 2, 3, 4],[2, 0, 0, 2],[3, 1, 1, 0]])

np.hsplit(z,2)

[array([[1, 2],
        [2, 0],
        [3, 1]]),
 array([[3, 4],
        [0, 2],
        [1, 0]])]

## **Ejercicio 16)** Generando números aleatorios

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.

**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.

In [73]:
# 16.1)